source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AZNetworking_Example', :exclusive => true do
  pod "AZNetworking", :path => "../"
end

target 'AZNetworking_Tests', :exclusive => true do
  pod "AZNetworking", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
